spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  application:
    name: service-feignww

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

server:
  port: 8084

oos:
  accessKeyId: LTAIIey7GYbMA2sf
  bucketName: erp-img1806
  accessKeySecret: hIdoPxkbmAKbgCoIisCtimV8WbWABX
  endpoint: http://oss-cn-beijing.aliyuncs.com
